### ISSUE TITLE
Update `network` tasks to support new module schema for `vmware_guest_network` 

### ISSUE THREAD

**Issue by robrakaric** [robrakaric/ansible-vmware-provisioning#2]
The current network tasks in `/roles/provision.vmware/tasks/network.yml` use an older schema for the `community.vmware.vmware_guest_network` module:

```yaml
networks:
  - state: absent
    label: "Network adapter 1"
```

It needs to look like this:

```yaml
mac_address: "{{ mac_address}}"
state: 'absent'
```

It might be in `"{{ clone.results }}"` (like clone.results.network.eth0.mac_address, or similar).

If it is not in `clone.results`, extract it from an info or facts module.
